[project]
name = "hello-pytesseract"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pillow>=11.0.0",
    "pytesseract>=0.3.13",
]
